---
- name: Run venv root tasks
  ansible.builtin.include_tasks:
    file: root.yml
    apply:
      become: yes

- name: Run venv user tasks
  ansible.builtin.include_tasks:
    file: user.yml
    apply:
      become: yes
      become_user: compute
