---
# Hardware v0.1 Configuration (A770)
control_host: "control_0_1"
compute_interface: "enx8cae4cf44e21"
arch: "amd64"
debootstrap_arch: "amd64"

compute_nodes:
  - {
      mac: "d8:bb:c1:9b:84:8b",
      ip: "{{ compute_subnet }}.101",
      name: "compute1",
    }

gpu_driver_role: "hardware_specific/intel_arc_drivers"
