---
# Hardware v0.1 Configuration
control_host: "control_0_1"
# Interface on the control node facing the compute nodes
compute_interface: "enx8cae4cf44e21"
# Interface on the compute nodes facing the control node
control_interface: enp6s0
arch: "amd64"
debootstrap_arch: "amd64"
rocm_arch: "gfx1200"

compute_nodes:
  - mac: "d8:bb:c1:a2:3e:a3"
    ip: "{{ compute_subnet }}.100"
    name: "compute0"
  - mac: "d8:bb:c1:9b:84:8b"
    ip: "{{ compute_subnet }}.101"
    name: "compute1"

llama_cpp_models:
  - hf-repo: bartowski/Mistral-Small-Instruct-2409-GGUF
    hf-file: Mistral-Small-Instruct-2409-Q4_K_L.gguf
  - hf-repo: unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF
    hf-file: Qwen3-Coder-30B-A3B-Instruct-Q6_K.gguf

# llama_server_model: Qwen3-Coder-30B-A3B-Instruct-Q6_K.gguf
llama_server_model: Mistral-Small-Instruct-2409-Q4_K_L.gguf

vllm_models:
  - hf-repo: AMead10/Mistral-Small-Instruct-2409-awq
    hf-file: Mistral-Small-Instruct-2409-awq

hardware_compute_configure_roles:
  - "hardware_specific/amd_vllm_build"
  - "hardware_specific/ray_worker"

hardware_control_configure_roles:
  - "hardware_specific/amd_radeon_drivers"
  - "hardware_specific/amd_vllm_build"
  - "hardware_specific/ray_head"

hardware_golden_image_roles:
  - "hardware_specific/amd_radeon_drivers"
  # - "hardware_specific/amd_llama_cpp_rpc_server"
  - "hardware_specific/amd_vllm_build"
  - "hardware_specific/ray_worker"

hardware_compute_test_roles:
  - "hardware_specific/amd_radeon_drivers"
  # - "hardware_specific/amd_llama_cpp_rpc_server"
