---
# Hardware v0.1 Configuration
control_host: "control_0_2"
build_host: "build_0_2"
# Interface on the control node facing the compute nodes
compute_interface: enp1s0 # TODO(antti) change this, neccessary to configure pxe and stuff correctly
# Interface on the compute nodes facing the control node
control_interface: enp191s0 # important for vllm stuff but not for initial boot
arch: "amd64"
debootstrap_arch: "amd64"
rocm_arch: "gfx1151" # AFAIK this is correct for strix-halo

compute_nodes:
  - mac: "9c:bf:0d:00:e6:79"
    ip: "192.168.10.104"
    name: "node4"
  - mac: "9c:bf:0d:00:ea:e4"
    ip: "192.168.10.103"
    name: "node3"
  - mac: "9c:bf:0d:00:e3:86"
    ip: "192.168.10.102"
    name: "node2"
  - mac: "9c:bf:0d:00:e7:9b"
    ip: "192.168.10.101"
    name: "node1"

llama_cpp_models:
  - hf-repo: unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF
    hf-file: Qwen3-Coder-30B-A3B-Instruct-Q6_K.gguf

llama_server_model: Qwen3-Coder-30B-A3B-Instruct-Q6_K.gguf

vllm_models: []

hardware_compute_configure_roles: []
hardware_control_configure_roles: []
hardware_golden_image_roles: []
hardware_compute_test_roles: []
