- name: Enable Wake-on-LAN for all ethernet interfaces
  ansible.builtin.copy:
    dest: /etc/systemd/network/99-wol.link
    content: |
      [Match]
      Name=en*

      [Link]
      WakeOnLan=magic
    mode: "0644"
