compute_subnet: 192.168.10
control_node_ip: "{{ compute_subnet }}.1"

golden_image_build_outer_dir: "{{ real_user_dir }}/build/{{ hardware_version }}"
golden_image_build_dir: "{{ real_user_dir }}/build/{{ hardware_version }}/ubuntu_golden"
golden_image_nfs_dir: "/srv/nfs/ubuntu_golden"
# golden_image_build_outer_dir: "/srv/nfs/ubuntu_golden"
# olden_image_build_dir: "/srv/nfs/ubuntu_golden"

llama_cpp_git_hash: c7be9feb
llama_cpp_rpc_port: 50052
llama_server_port: 8080
llama_cpp_models_dir: /opt/models/llama_cpp
llama_cpp_source_dir: /usr/local/src/llama.cpp
llama_cpp_build_dir: "{{ llama_cpp_source_dir }}/build-rpc-rocm"

vllm_models_dir: /opt/models/vllm
vllm_venv_path: /opt/venvs/vllm
vllm_source_path: /usr/local/src/vllm
vllm_ray_port: 6379
