---
- name: Clean up and remove the golden image
  hosts: localhost
  become: true
  tasks:
    - name: Ensure chroot filesystems are unmounted
      ansible.builtin.include_role:
        name: control/chroot_connection_cleanup

    - name: Stop and disable the NFS server
      ansible.builtin.service:
        name: nfs-kernel-server
        state: stopped
        enabled: false
      register: service_status
      failed_when:
        - service_status.failed
        - "'not found' not in service_status.msg | lower"

    - name: Remove the golden image directory
      ansible.builtin.file:
        path: /srv/nfs/ubuntu_golden
        state: absent
