---
- hosts: localhost
  connection: local
  become: yes
  vars_files:
    - "hardware_vars/{{ hardware_version }}.yml"

  tasks:
    - name: Run IPEX LLM verification
      include_role:
        name: hardware_specific/ipex_llm
        tasks_from: verify.yml
