---
- name: Test control node configuration
  hosts: localhost
  connection: local
  become: true
  vars_files:
    - "hardware_vars/{{ hardware_version }}.yml"

  tasks:
    - name: Run IPEX LLM verification
      ansible.builtin.include_role:
        name: ipex_llm
        tasks_from: verify.yml
