- name: Get and print the broadcast address for the compute interface
  hosts: localhost
  connection: local
  vars_files:
    - vars/main.yml
  tasks:
    - name: Get interface facts
      ansible.builtin.setup:
        filter: "ansible_facts['{{ compute_interface }}']"

    - name: Print broadcast address
      ansible.builtin.debug:
        msg: "{{ ansible_facts[compute_interface]['ipv4']['broadcast'] }}"
