name: Golden Image Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: "geerlingguy/docker-ubuntu2404-ansible:latest"
      options: --privileged --cgroupns=host
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:rw
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: "Patch APT Sources to use Azure Mirrors and update"
        run: |
          # Use sed to replace the standard Ubuntu archives with the Azure mirrors.
          # This is the key to preventing "Too Many Requests" errors with the ubunut apt servers
          sudo sed -i 's#http://archive.ubuntu.com/ubuntu/#http://azure.archive.ubuntu.com/ubuntu/#' /etc/apt/sources.list.d/ubuntu.sources
          sudo sed -i 's#http://security.ubuntu.com/ubuntu/#http://azure.archive.ubuntu.com/ubuntu/#' /etc/apt/sources.list.d/ubuntu.sources

          sudo apt update -y

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build and Configure Image
        run: |
          ansible-playbook ansible/build_image.yml --extra-vars 'hardware_version=test_mock' --become
          sudo -E ansible-playbook ansible/golden_image_configure.yml --extra-vars 'hardware_version=test_mock' --become
      # - name: Package Image
      #   run: |
      #     tar -czf image-test-mock.tar.gz -C ~/build/test_mock/ubuntu_golden .
      # - name: Upload Image Artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: image-test-mock
      #     path: image-test-mock.tar.gz
